name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment tag variables
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Docker build and push to dockerhub
        run: |
          docker build \
            --tag $DOCKER_USERNAME/$REPOSITORY_NAME:$RELEASE_VERSION \
            --tag $DOCKER_USERNAME/$REPOSITORY_NAME:latest . \
          docker image push --all-tags
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
